GET http://localhost:3000/comics
Content-Type: application/json

###
POST http://localhost:3000/users/registro
Content-Type: application/json

{
    "nombre":"Antonio",
    "usuario": "Tonieras",
    "email": "tonieras@gmail.com",
    "password": "qwerty123",
    "rol": ""
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"alwaromoreno@gmail.com",
    "password": "qwerty123"
}