GET http://localhost:3000/comics
Content-Type: application/json


###
GET http://localhost:3000/comics/3
Content-Type: application/json

###
POST http://localhost:3000/users/registro
Content-Type: application/json

{
    "nombre":"Antonio",
    "usuario": "Tonieras",
    "email": "tonieras@gmail.com",
    "password": "qwerty123",
    "rol": ""
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"anita@gmail.com",
    "password": "qwerty123"
}

###

GET http://localhost:3000/users/login/boketto.producciones@gmail.com


###
DELETE http://localhost:3000/comics/10



###
GET http://localhost:3000/users/anitaheart

###
PUT http://localhost:3000/comics/edit/31
Content-Type: application/json

{
    "titulo": "tuputamadre",
    "autor":"asfgh",
    "dibujante":"dfbn",
    "ano":"",
    "genero":"dsffgh",
    "escuela":"manga",
    "editorial":"FFFFFFFFFFF",
    "descripcion":"FFFFFFF",
    "nombreArchivo":"",
    "linkFoto":"",
    "archivo":"",
    "fk_autor":"3"
}



###
GET http://localhost:3000/autores
Content-Type: application/json


###
GET http://localhost:3000/autores/31
Content-Type: application/json

###
PUT http://localhost:3000/autores/edit/31
Content-Type: application/json

{
    "nombre": "Jajajaaj",
    "biografia":"Nací en la calle"
}

###

GET  http://localhost:3000/indices/63

###
POST http://localhost:3000/indices/tbi/63/4

###
PUT http://localhost:3000/indices/page/63/2/4

###
PUT http://localhost:3000/indices/updateStatus/1491/leyendo

###

GET http://localhost:3000/indices/getpage/63/5



